spring:
  datasource:
    hikari:
      connection-timeout: '20000'
      maximum-pool-size: '5'
    password: colportores2025
    username: servicecolportores
    url: jdbc:postgresql://localhost:5432/colportores
  application:
    name: colportores-crud
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  servlet:
    context-path: /colportores-crud
  port: '0'


eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/